export enum CHECK_RESULT_CODES {
  ALL_OTHER_CHECKS_FAILED = "ALL_OTHER_CHECKS_FAILED",
  NO_PREVIOUS_EVENT_TO_COMPARE = "NO_PREVIOUS_EVENT_TO_COMPARE",
  PAST_TIMESTAMP_EVENT = "PAST_TIMESTAMP_EVENT",
  ENOUGH_TIME_PASSED = "ENOUGH_TIME_PASSED",
  DELTA_MODULE_IS_BIGGER = "DELTA_MODULE_IS_BIGGER",
  VECTORS_DONT_MATCH = "VECTORS_DONT_MATCH",
  HIGH_VELOCITY_NON_DECREASING_DELTAS = "HIGH_VELOCITY_NON_DECREASING_DELTAS",
  NON_DECREASING_DELTAS_OF_KNOWN_HUMAN = "NON_DECREASING_DELTAS_OF_KNOWN_HUMAN",
  ANOMALY_INERTIA_JUMP = "ANOMALY_INERTIA_JUMP",
}
